package io.github.yuroyami.kiteimage

import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

/**
 * Vectors generated by `gen_png_vectors.py` (python3's zlib — an implementation
 * independent from both this decoder and its references). Expected pixels are
 * knowable by construction; the generator's comments state each one.
 */
class PngDecoderTest {

    // gray8 4x4 gradient; rows filtered None/Sub/Up/Paeth
    private val GRAY8_4X4 = "89504e470d0a1a0a0000000d49484452000000040000000408000000008c9ac1a2000000184944415478da6360e0129163d4e0e2e262d2000216100b000d5701704e711c6a0000000049454e44ae426082"

    // rgb8 3x3; rows filtered None/Average/Paeth
    private val RGB8_3X3 = "89504e470d0a1a0a0000000d4948445200000003000000030802000000d94a22e8000000234944415478da63f8cfc0c000c6ccdd2272ca2b758dccf7b2ec6b72cb6a9eb3f3ec7f008d9f0b755792e1b00000000049454e44ae426082"

    // palette 4x2 (red/green/blue/yellow), tRNS = [0, 128]
    private val PAL8_4X2 = "89504e470d0a1a0a0000000d494844520000000400000002080300000048768d510000000c504c5445ff000000ff000000ffffff00d6028f7b0000000274524e5300809b2b4e18000000124944415478da6360606462666066626400000046000da400597b0000000049454e44ae426082"

    // rgba8 2x2 with genuine alpha; second row Sub-filtered
    private val RGBA8_2X2 = "89504e470d0a1a0a0000000d494844520000000200000002080600000072b60d24000000174944415478da63f8cfc0f01f081b1881b4c3ffff0c07003ee3077ce9dbb2f80000000049454e44ae426082"

    // gray1 8x1, bit pattern 10110010
    private val GRAY1_8X1 = "89504e470d0a1a0a0000000d4948445200000008000000010100000000cb7bd2ee0000000a4944415478da63d8040000b400b38990cd2f0000000049454e44ae426082"

    // gray16 2x1, samples 0x1234 and 0xFF00 → high bytes 0x12, 0xFF
    private val GRAY16_2X1 = "89504e470d0a1a0a0000000d494844520000000200000001100000000081d9fc150000000d4944415478da631032f9cf000002e70146a0a59e520000000049454e44ae426082"

    // rgb8 2x1 with tRNS color key (10,20,30); first pixel matches the key
    private val RGB8_COLORKEY_2X1 = "89504e470d0a1a0a0000000d49484452000000020000000108020000007b40e8dd0000000674524e53000a0014001ec53629ff0000000f4944415478da63e01291e3129107000184007a25e47c910000000049454e44ae426082"

    // gray4 3x1, samples 15/0/9 → ×17 → 255/0/153
    private val GRAY4_3X1 = "89504e470d0a1a0a0000000d4948445200000003000000010400000000fb7ba6690000000b4944415478da63f83001000273018135beca680000000049454e44ae426082"

    // gray+alpha8 2x1: (100, a=255), (200, a=0)
    private val GRAYA8_2X1 = "89504e470d0a1a0a0000000d49484452000000020000000108040000005e2bb7010000000d4944415478da6348f97f8201000622022cd56c96430000000049454e44ae426082"

    // 1x1 with the Adam7 interlace flag set
    private val INTERLACED_1X1 = "89504e470d0a1a0a0000000d49484452000000010000000108000000014d79abc30000000a49444154789c636000000002000148afa4710000000049454e44ae426082"

    // 1x1 whose IDAT CRC has one flipped byte
    private val BAD_CRC_1X1 = "89504e470d0a1a0a0000000d49484452000000010000000108000000003a7e9b550000000a4944415478da63d00200002c002b61f292940000000049454e44ae426082"

    @Test
    fun gray8AllFourFilters() {
        val bm = KiteImage.decode(hex(GRAY8_4X4))
        assertEquals(4, bm.width)
        assertEquals(4, bm.height)
        val expected = IntArray(16) { gray(it % 4 * 10 + it / 4 * 40) }
        assertContentEquals(expected, bm.argb)
    }

    @Test
    fun rgb8AverageAndPaethFilters() {
        val bm = KiteImage.decode(hex(RGB8_3X3))
        val e = intArrayOf(
            argb(0xFF, 255, 0, 0), argb(0xFF, 0, 255, 0), argb(0xFF, 0, 0, 255),
            argb(0xFF, 10, 20, 30), argb(0xFF, 40, 50, 60), argb(0xFF, 70, 80, 90),
            argb(0xFF, 200, 150, 100), argb(0xFF, 50, 25, 0), argb(0xFF, 255, 255, 255),
        )
        assertContentEquals(e, bm.argb)
    }

    @Test
    fun paletteWithPartialTrns() {
        val bm = KiteImage.decode(hex(PAL8_4X2))
        val red0 = argb(0x00, 255, 0, 0)      // tRNS[0] = 0
        val green128 = argb(0x80, 0, 255, 0)  // tRNS[1] = 128
        val blue = argb(0xFF, 0, 0, 255)      // beyond tRNS → opaque
        val yellow = argb(0xFF, 255, 255, 0)
        assertContentEquals(intArrayOf(red0, green128, blue, yellow, yellow, blue, green128, red0), bm.argb)
        assertTrue(bm.hasTransparency())
    }

    @Test
    fun rgba8RealAlpha() {
        val bm = KiteImage.decode(hex(RGBA8_2X2))
        assertContentEquals(
            intArrayOf(
                argb(0xFF, 255, 0, 0), argb(0x80, 0, 255, 0),
                argb(0x40, 0, 0, 255), argb(0x00, 255, 255, 255),
            ),
            bm.argb,
        )
    }

    @Test
    fun gray1BitPacking() {
        val bm = KiteImage.decode(hex(GRAY1_8X1))
        // 10110010, MSB first
        val bits = intArrayOf(1, 0, 1, 1, 0, 0, 1, 0)
        assertContentEquals(bits.map { gray(it * 255) }.toIntArray(), bm.argb)
    }

    @Test
    fun gray16ReducesToHighByte() {
        val bm = KiteImage.decode(hex(GRAY16_2X1))
        assertContentEquals(intArrayOf(gray(0x12), gray(0xFF)), bm.argb)
    }

    @Test
    fun rgbColorKeyTransparency() {
        val bm = KiteImage.decode(hex(RGB8_COLORKEY_2X1))
        assertContentEquals(
            intArrayOf(argb(0x00, 10, 20, 30), argb(0xFF, 10, 20, 31)),
            bm.argb,
        )
    }

    @Test
    fun gray4SubByteRow() {
        val bm = KiteImage.decode(hex(GRAY4_3X1))
        assertContentEquals(intArrayOf(gray(255), gray(0), gray(153)), bm.argb)
    }

    @Test
    fun grayAlphaPair() {
        val bm = KiteImage.decode(hex(GRAYA8_2X1))
        assertContentEquals(intArrayOf(argb(0xFF, 100, 100, 100), argb(0x00, 200, 200, 200)), bm.argb)
    }

    @Test
    fun interlacedOnePixelDecodes() {
        // A 1x1 Adam7 file is just pass 1 with a single pixel.
        val bm = KiteImage.decode(hex(INTERLACED_1X1))
        assertEquals(1, bm.width)
        assertEquals(gray(0), bm[0, 0])
    }

    @Test
    fun corruptCrcRejected() {
        assertFailsWith<ImageDecodeException> { KiteImage.decode(hex(BAD_CRC_1X1)) }
    }

    @Test
    fun truncationsNeverCrash() {
        val whole = hex(RGBA8_2X2)
        for (cut in intArrayOf(0, 4, 8, 20, 33, whole.size - 5, whole.size - 1)) {
            assertFailsWith<ImageDecodeException>("cut at $cut") {
                KiteImage.decode(whole.copyOf(cut))
            }
        }
    }
}
